project:
  type: website
  output-dir: docs
  
website:
  title: "Ariana Mendible"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd
      #- text: "Projects"
      #  menu:
       # - academic_projects.qmd
       # - personal_projects.qmd
      - text: CV
        href: assets/files/mendible_cv.pdf
    background: "#c0d6df"
  favicon: assets/img/favicon.png


format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: true

editor: visual

resources:
  - CNAME
  - custom.scss