project:
  type: website
  output-dir: docs
  
website:
  title: "Ariana Mendible"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd
      #- text: "Projects"
      #  menu:
       # - academic_projects.qmd
       # - personal_projects.qmd
      - text: CV
        href: assets/files/mendible_cv.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

resources:
  - CNAME
