---
title: "Teaching"
---

I teach a mix of data science and math courses Seattle University-- my main emphasis is in the MS Data Science program. In all my classes, I place a strong emphasis on critical thinking, applying knowledge to real-world problems, and communication skills. I wrote an [article in COMAP's GAIMME Time](https://www.comap.com/membership/member-resources/item/gaimme-time-getting-away-from-one-right-answer?highlight=WyJtZW5kaWJsZSJd) (Guidelines for Assessment and Instruction in Mathematical Modeling Education) column about these goals. 

If you teach similar courses and would like to share resources and ideas, please get in touch!

### Courses

- DATA 5322: Statistical Machine Learning II
- DATA 5901 & 5902: MSDS Capstone series
- DATA 3310 & 5310: Data Visualization
- MATH 1335: Calculus II (Integral Calculus)

### Teaching Resources

- [QSIDE Data4Justice Curriculum](https://qsideinstitute.org/data4justice-curriculum/)
- [Curriculum for data visualization](https://uwdata.github.io/visualization-curriculum/intro.html) using Altair, Python's grammar of graphics plotting package 
- An Introduction to Statistical Learning by James, Witten, Hastie and Tibshirani, [a texbook for machine learning, available in R and Python](https://www.statlearning.com/)
- [The Craft of Community Engaged Teaching and Learning](https://www.google.com/books/edition/The_Craft_of_Community_Engaged_Teaching/p5StDwAAQBAJ) by Marshall Welch and Star Plaxton-Moore
- Laziness Does Not Exist by Devon Price, [blog post](https://humanparts.medium.com/laziness-does-not-exist-3af27e312d01) and [full book](https://www.google.com/books/edition/Laziness_Does_Not_Exist/FvztDwAAQBAJ)